#spring设置
spring:
  #数据源
  datasource:
    #mysql连接
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    # useSSL=false忽略警告
    url: jdbc:mysql://localhost:3306/sqmall?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mappers/*.xml

logging:
  pattern:
    console: "[%thread] %-5level %logger{36} - %msg%n"
